name: Auto Commit LeetCode Solutions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '12 7 * * *'  # Runs daily at 12:42 PM IST (7:12 AM UTC)

  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Make the Script Executable
        run: chmod +x commit_and_push.sh

      - name: Run Commit and Push Script
        run: ./commit_and_push.sh
