name: Auto Commit LeetCode Solutions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '45 18 * * *'  # Runs daily at 6:45 PM UTC
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Make the Script Executable
        run: chmod +x commit_and_push.sh

      - name: Run Commit and Push Script
        run: ./commit_and_push.sh
